import air
import inspect
from air_markdown import Markdown
from fastapi import HTTPException
from fastapi import FastAPI
from pathlib import Path
from tags import FeldroyLogo

app = air.Air()
api = FastAPI()

app.mount("/static", air.StaticFiles(directory="static"), name="static")


def nav():
    return air.Nav(
        air.A("Home", href="/"),
        air.A("Usage Policy", href="/usage-policy"),
    )


def footer():
    return air.Footer(
        air.P(
            "© 2025 Feldroy. All rights reserved. This website is powered by ",
            air.A("Air", href="https://air.feldroy.com"),
            " 🌬️ View the source code on ",
            air.A("GitHub", href="https://github.com/feldroy/feldroy-svgs")
        )
    )


@app.page
def index():
    return air.layouts.mvpcss(
        nav(),
        air.Title("Feldroy SVGs"),
        air.H1("The Feldroy logo as SVG and Air Tag"),
        air.P("This page contains the Feldroy logo in SVG format, as well as inline SVG code generated by calling the FeldroyLogo() Air Tag."),

        air.Img(src="/static/feldroy-logo-square.svg", alt="Feldroy Logo", width=200, height=200),

        air.Div(
            air.A(
                "Download SVG",
                href="/static/feldroy-logo-square.svg",
                download=True,
            ),
        ),
        air.P("Here is the SVG code for the above logo:"),
        air.Pre(
            air.Code(
                Path("static/feldroy-logo-square.svg").read_text(),
                lang="xml"
            )
        ),
        air.P("Here it is used as an Air Tag:"),
        FeldroyLogo(),
        air.P("To use the FeldroyLogo Air Tag in an Air app, you just do:"),
        air.Pre(
            air.Code(
                "from tags import FeldroyLogo\n\n"
                "def index():\n"
                "    return FeldroyLogo()\n",
                lang="python"
            )
        ),
        air.P("Under the hood, the FeldroyLogo tag generates the SVG code shown earlier. In tags.py you can see it is constructed with this Python code:"),
        air.Pre(
            air.Code(
                inspect.getsource(FeldroyLogo),
                lang="python"
            )
        ),
        
        
        footer()
    )


def layout(request: air.Request, *content):
    if not isinstance(request, air.Request):
        raise Exception('First arg of layout needs to be an air.Request')
    return air.layouts.mvpcss(
        nav(),
        *content,
        footer()
    )


@app.get('/{slug:path}')
def mdpage(request: air.Request, slug: str):
    path = Path(f"pages/{slug}.md")
    if path.exists():
        text = path.read_text()
        # TODO add fetching of page title from first H1 tag
        return layout(
            request, Markdown(text)
        )
    path = Path(f"pages/{slug}.py")
    if path.exists():
        module_name = f'pages.{slug.replace('/', '.')}'     
        mod = importlib.import_module(module_name)
        return layout(
            request, mod.render(request)
        )
    raise HTTPException(status_code=404)


if __name__ == "__main__":
    print("Run this with fastapi dev")
